baseurl = "//declangraymullen.com/"
title = "Declan Gray-Mullen"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "graydh"

[params]
    author = "Declan Gray-Mullen"
    info = "CS Major @ UMass Amherst CHC"
    description = "Declan's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "/images/declaniconavatar.jpg"

    favicon_32="/images/icons8-raspberrypi.png"
    favicon_16 = "/images/icons8-raspberrypi.png"

    footercontent = ""

    hidecredits = true
    hidecopyright = true

    inverted = true

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/graydh/"
[[params.social]]
    name = "Linkedin"
    icon = "fab fa-linkedin fa-2x"
    weight = 2
    url = "https://www.linkedin.com/in/declangray-mullen/"
[[params.social]]
    name = "Handshake"
    icon = "fas fa-handshake fa-2x"
    weight = 3
    url = "https://app.joinhandshake.com/users/10647344"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 2
    url  = "/blog/"
[[menu.main]]
    name = "About"
    weight = 1
    url = "/about"
[[menu.main]]
    name = "Contact Me"
    weight = 4
    url = "mailto:dgraymullen@umass.edu"
[[menu.main]]
    name = "Projects"
    weight = 3
    url = "/projects/"